{
 "title": "Docker Containers",
 "description": "Containers metrics",
 "tags": [ "docker" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[1m])) / count(node_cpu_seconds_total{mode=\"user\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "machine_cpu_cores" }
   ]
  },
  {
   "title": "Memory Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})"
    }
   ]
  },
  {
   "title": "Storage Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{fstype=\"ext4\"} - node_filesystem_free_bytes{fstype=\"ext4\"}) / node_filesystem_size_bytes{fstype=\"ext4\"}  * 100"
    }
   ]
  },
  { "title": "Alerts Panel", "type": "alertlist", "gridPos": { "h": 4, "w": 4, "x": 17, "y": 0 } },
  {
   "title": "Used Storage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(container_fs_usage_bytes)" }
   ]
  },
  {
   "title": "Running Containers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "scalar(count(container_memory_usage_bytes{image!=\"\"}) > 0)",
     "legendFormat": "containers"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "load 1m" }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image!=\"\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image!=\"\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Cached Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (container_memory_cache{image!=\"\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{image!=\"\"}[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\"}[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}